### ISSUE TITLE
Separate option for Ads and Trackers.

### ISSUE THREAD

**Issue by ghost** [brave/adblock-resources#156]
Need separate option for Ads and Trackers. Because, for the sake of blocking all ads if I select **Trackers & ads blocking** to **Aggressive** on Shields the problem of website breaking arise and in order to prevent website breakage if I select **Trackers & ads blocking** to **Standard** then some ads not getting blocked. So, My humble request kindly introduce two separate options so that one can select **Ads blocking to Aggressive** and **Trackers blocking to Standard**.

@antonok-edm 
@ryanbr

**Comment by ryanbr** [comment]
Everything is combined in our default rules, would add another level of complexity. Adding yet more options/changes to shields isn't ideal. 

I don't see a place where you would want to disable one but enable the other?
