### ISSUE TITLE
Add my Nordic list

### ISSUE THREAD

**Issue by DandelionSprout** [brave/adblock-resources#9]
My list is now possibly the **only** regional list that is included in uBO but not in Brave, not to mention it's just ~2 weeks away from being included in ABP as well, so I'd say it's about time to add it to Brave. Details:

        "url": "https://raw.githubusercontent.com/DandelionSprout/adfilt/master/NorwegianExperimentalList%20alternate%20versions/NordicFiltersBrave.txt",
        "title": "Dandelion Sprout's Nordic Filters",
        "format": "Standard",
        "langs": ["nb", "nn", "no", "da", "is"],
        "support_url": "https://github.com/DandelionSprout/adfilt/issues",
        "desc": "Removes advertisements from Norwegian, Danish and Icelandic websites"

Alternately the URL can be replaced with `"https://raw.githubusercontent.com/DandelionSprout/adfilt/master/NorwegianList.txt",`, depending on which one you feel has the more suitable syntax both currently and in the near future.

**Comment by bsclifton** [comment]
cc: @ryanbr @pes10k

**Comment by pes10k** [comment]
@ryanbr / @antonok-edm do we need to resync our regional lists?  I know we have occasional licensing issues too, and https://github.com/DandelionSprout/adfilt/blob/master/LICENSE.md looks like a bespoke issue.  

If ya'll want to include this one, we'll have to run it by legal.  Or, @DandelionSprout, any chance of also licensing it in a more permissive / common way (or even just a public statement that Brave can use it, so long as we dont X Y Z)?  Not trying to make things tricky, but pulling in resources with uncommon licenses has been a concern in the past, and just seeing what we can do to make things easier for all of us :)

(In otherwords, please dont take my licensing request as any kind of demand or nothing, just looking to see if / where we can simplfiy things in a mutually agreeable way :) )

**Comment by DandelionSprout** [comment]
I created that particular licence so that I could explain to people that yes, my lists could be used for practically anything whatsoever for almost any purpose (Mostly the same way as BSD-3); but I also felt I had to make some encapsulation provisions to try to avoid pissing off hardcore GPL-3.0 fanboys that are out there on GitHub.

I've been meaning to simplify the licence's text, but it'd be a big task and would most likely take me 1-2 weeks.

**Comment by DandelionSprout** [comment]
Okay, so after [rewriting my licence fairly heavily](https://github.com/DandelionSprout/Dandelicence/blob/master/DandelicenceV1.3.md) (which took a whole lot less time than expected):

Invoking clause §4c in Dandelicence V1.3, I officially grant Brave Software, Inc. full permission to use, utilise, modify and redistribute content from https://github.com/DandelionSprout/adfilt (except for those paragraphs of *[YouTube: Even More Pure Video Experience](https://github.com/DandelionSprout/adfilt/blob/master/YouTubeEvenMorePureVideoExperience.txt)* or *[Staying On The Phone Browser](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/stayingonbrowser/Staying%20On%20The%20Phone%20Browser)* that contain entries I borrowed from other lists) in absolutely any way they want to, as long as §2 and §7 are followed.

**Comment by ryanbr** [comment]
Reviewing: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/NorwegianList.txt @DandelionSprout 

I still don't understand why, `domain=~ [comments]` exist when we have `!`
`||adidasko.com^$doc,domain=~ Advarselen vises grunnet: En grovt falsk nettbutikksvindel som er svartelistet av Forbrukertilsynet.`
`||fintechnow*.buzz^$doc,domain=~ Advarselen vises grunnet: Bitcoin-svindel`

Creating weird hacks seems strange when it's not even needed.

**Comment by DandelionSprout** [comment]
The reason is very simple. It allows me to do this: https://user-images.githubusercontent.com/22780683/86959905-fdf50000-c15e-11ea-992f-963c896e4791.png

I'd estimate that 75% of uBlock Origin's oftentimes very casual users, are very unfamiliar with the strictblock screen and are thinking their PCs got hacked. So these messages are alpha and omega in my uBO-specific lists.

**Comment by DandelionSprout** [comment]
Okay, so in what was (for me) an unexpected turn of events, I've now removed those comment tricks anyway, because they were broken by uBO's linter that was introduced 1-2 months ago.

Thus I presume the main obstacle-ish thing that prevented the addition of my list in Brave, is no longer a problem factor.

**Comment by ryanbr** [comment]
Ok, will create a patch this week, thanks for the changes

**Comment by MasterKia** [comment]
@pes10k Sorry about reviving a 2 years old issue but technically speaking (and for my own curiosity sake), can a _non-GPL_ browser (i.e. Brave) include a _GPL_ filterlist (i.e. uBO uAssets lists and the EasyList [which is GPL](https://easylist.to/pages/licence.html))?

In the software side of things, someone can't use GPL code in their own non-GPL software; but this is a filterlist we're talking about so I assume things might be different?

**Comment by pes10k** [comment]
@MasterKia my (non lawyer) understanding is that it is fine for non-GPL software to reference/point to GPL lists and resources, as long as we don't bundle it or distribute it ourselves.  This is very very very not a legal-expert comment though, only my best effort to accurately repeat my understanding of the law / license

**Comment by MasterKia** [comment]
Thanks for the perspective, it makes sense.

Although to my knowledge there is another license, the LGPL which was created to _allow_ **_linking_** from other non-GPL (even proprietary) software. So what we see is that today a lot of important libraries use LGPL instead of GPL.



> as long as we don't bundle it or distribute it ourselves

I think this is a fair point, if Brave downloads the list _only_ when it's enabled by the user then there is no distribution/bundling involved and nothing to worry about (I guess).
